# Generated by Django 4.0.2 on 2022-06-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.TextField(max_length=255, verbose_name='Username')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('confirm_password', models.CharField(max_length=50, verbose_name='Confirm Password')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Note')),
            ],
        ),
    ]
