# Generated by Django 4.0.2 on 2022-06-19 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_customers_user_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_sign',
            name='user_name',
            field=models.CharField(max_length=255, verbose_name='Username'),
        ),
    ]
