# Generated by Django 4.0.2 on 2022-06-20 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_user_sign_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_sign',
            name='content',
        ),
    ]
