# Generated by Django 4.0.2 on 2022-06-20 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_user_sign_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=255, verbose_name='Username')),
                ('Password', models.CharField(max_length=50, verbose_name='Password')),
                ('Confirm_Password', models.CharField(max_length=50, verbose_name='Confirm Password')),
                ('Email', models.EmailField(max_length=255, verbose_name='Email')),
            ],
        ),
        migrations.DeleteModel(
            name='User_Sign',
        ),
    ]
