# Generated by Django 4.0.2 on 2022-06-20 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_signup_delete_user_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='Confirm_Password',
            field=models.CharField(max_length=50, verbose_name='Confirm_Password'),
        ),
    ]
