# Generated by Django 4.0.2 on 2022-06-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_signup_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_name', models.CharField(max_length=255, verbose_name='Username')),
                ('Password', models.CharField(max_length=50, verbose_name='Password')),
            ],
        ),
        migrations.AlterField(
            model_name='signup',
            name='Confirm_Password',
            field=models.CharField(max_length=50, verbose_name='Confirm Password'),
        ),
    ]
